#include "SPerformanceOptimizerTab.h"

#include "Dom/JsonObject.h"
#include "IPythonScriptPlugin.h"
#include "LevelEditorViewport.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Styling/AppStyle.h"
#include "Styling/CoreStyle.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SCheckBox.h"
#include "Widgets/Layout/SBorder.h"
#include "Widgets/Layout/SScrollBox.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/Text/STextBlock.h"

#define LOCTEXT_NAMESPACE "PerformanceOptimizerUI"

namespace PerfUI
{
	static FString Str(const TSharedPtr<FJsonObject>& Obj, const TCHAR* Key)
	{
		FString Value;
		if (Obj.IsValid())
		{
			Obj->TryGetStringField(Key, Value);
		}
		return Value;
	}

	static bool Bool(const TSharedPtr<FJsonObject>& Obj, const TCHAR* Key)
	{
		bool bValue = false;
		if (Obj.IsValid())
		{
			Obj->TryGetBoolField(Key, bValue);
		}
		return bValue;
	}

	static const TArray<TSharedPtr<FJsonValue>>* Array(const TSharedPtr<FJsonObject>& Obj, const TCHAR* Key)
	{
		const TArray<TSharedPtr<FJsonValue>>* Values = nullptr;
		if (Obj.IsValid() && Obj->TryGetArrayField(Key, Values))
		{
			return Values;
		}
		return nullptr;
	}

	/** Item ids are generated by perf_optimizer.py; only allow [a-z0-9_] before putting them in a Python call. */
	static bool IsSafeId(const FString& Id)
	{
		if (Id.IsEmpty())
		{
			return false;
		}
		for (const TCHAR C : Id)
		{
			if (!((C >= 'a' && C <= 'z') || (C >= '0' && C <= '9') || C == '_'))
			{
				return false;
			}
		}
		return true;
	}

	static FLinearColor StatusColor(const FString& Status)
	{
		if (Status == TEXT("suggest"))
		{
			return FLinearColor(1.0f, 0.65f, 0.15f);
		}
		if (Status == TEXT("ok"))
		{
			return FLinearColor(0.35f, 0.8f, 0.35f);
		}
		if (Status == TEXT("warn"))
		{
			return FLinearColor(1.0f, 0.35f, 0.3f);
		}
		return FLinearColor(0.6f, 0.6f, 0.6f);
	}

	static FLinearColor RiskColor(const FString& Risk)
	{
		if (Risk == TEXT("None"))
		{
			return FLinearColor(0.35f, 0.8f, 0.35f);
		}
		if (Risk == TEXT("Low"))
		{
			return FLinearColor(0.75f, 0.85f, 0.35f);
		}
		if (Risk == TEXT("Medium"))
		{
			return FLinearColor(1.0f, 0.65f, 0.15f);
		}
		return FLinearColor(1.0f, 0.35f, 0.3f);
	}
}

void SPerformanceOptimizerTab::Construct(const FArguments& InArgs)
{
	ChildSlot
	[
		SNew(SVerticalBox)

		// Title + context
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 10.f, 12.f, 2.f)
		[
			SNew(STextBlock)
			.Text(LOCTEXT("Title", "Performance Improvements"))
			.Font(FCoreStyle::GetDefaultFontStyle("Bold", 16))
		]
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 0.f, 12.f, 8.f)
		[
			SNew(STextBlock)
			.Text(this, &SPerformanceOptimizerTab::GetHeaderText)
			.AutoWrapText(true)
			.ColorAndOpacity(FSlateColor::UseSubduedForeground())
		]

		// Main actions
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 0.f, 12.f, 4.f)
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot().AutoWidth().Padding(0.f, 0.f, 6.f, 0.f)
			[
				SNew(SButton)
				.Text(LOCTEXT("Scan", "Scan"))
				.ToolTipText(LOCTEXT("ScanTip", "Check project settings and the open level. Read-only."))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnScanClicked)
			]
			+ SHorizontalBox::Slot().AutoWidth().Padding(0.f, 0.f, 6.f, 0.f)
			[
				SNew(SButton)
				.Text(LOCTEXT("Auto", "Auto Optimize"))
				.ToolTipText(LOCTEXT("AutoTip", "Measure FPS, turn on the safe settings for this editor session, measure again and show the difference. Never edits levels or textures, never saves."))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnAutoClicked)
			]
			+ SHorizontalBox::Slot().AutoWidth().VAlign(VAlign_Center).Padding(0.f, 0.f, 12.f, 0.f)
			[
				SNew(SCheckBox)
				.IsChecked_Lambda([this]() { return bIncludeLowImpact ? ECheckBoxState::Checked : ECheckBoxState::Unchecked; })
				.OnCheckStateChanged_Lambda([this](ECheckBoxState NewState) { bIncludeLowImpact = NewState == ECheckBoxState::Checked; })
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.ToolTipText(LOCTEXT("LowTip", "Off: Auto Optimize only uses settings with NO visual change. On: also settings with a LOW visual change (slightly softer local-light shadows / GI, motion blur and lens flares off). Textures are never changed either way."))
				[
					SNew(STextBlock).Text(LOCTEXT("IncludeLow", "Allow low visual impact"))
				]
			]
			+ SHorizontalBox::Slot().AutoWidth().Padding(0.f, 0.f, 6.f, 0.f)
			[
				SNew(SButton)
				.Text(LOCTEXT("Measure", "Measure FPS"))
				.ToolTipText(LOCTEXT("MeasureTip", "Measure the editor viewport frame rate (uncapped). Measure again after toggling settings to compare."))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnMeasureClicked)
			]
			+ SHorizontalBox::Slot().AutoWidth()
			[
				SNew(SButton)
				.Text(LOCTEXT("Cancel", "Cancel"))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsBusy)
				.OnClicked(this, &SPerformanceOptimizerTab::OnCancelClicked)
			]
		]

		// Project actions
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 0.f, 12.f, 6.f)
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot().AutoWidth().Padding(0.f, 0.f, 6.f, 0.f)
			[
				SNew(SButton)
				.Text(LOCTEXT("Save", "Save to Project"))
				.ToolTipText(LOCTEXT("SaveTip", "Write the settings that are on to Config/DefaultEngine.ini [SystemSettings] (checked out in Perforce and backed up first) and remove the ones you turned off. Shows exactly what changes and asks first."))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnSaveClicked)
			]
			+ SHorizontalBox::Slot().AutoWidth().Padding(0.f, 0.f, 6.f, 0.f)
			[
				SNew(SButton)
				.Text(LOCTEXT("Revert", "Revert All"))
				.ToolTipText(LOCTEXT("RevertTip", "Turn off everything this tool turned on in this editor session."))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnRevertClicked)
			]
			+ SHorizontalBox::Slot().AutoWidth()
			[
				SNew(SButton)
				.Text(LOCTEXT("Report", "Open Report"))
				.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
				.OnClicked(this, &SPerformanceOptimizerTab::OnReportClicked)
			]
		]

		// Status line
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 2.f, 12.f, 4.f)
		[
			SNew(STextBlock)
			.Text(this, &SPerformanceOptimizerTab::GetStatusText)
			.AutoWrapText(true)
		]

		// Before / after results
		+ SVerticalBox::Slot()
		.AutoHeight()
		.Padding(12.f, 0.f, 12.f, 6.f)
		[
			SNew(SBorder)
			.Visibility(this, &SPerformanceOptimizerTab::GetResultsVisibility)
			.BorderImage(FAppStyle::GetBrush("ToolPanel.GroupBorder"))
			.Padding(FMargin(10.f, 8.f))
			[
				SNew(STextBlock)
				.Text(this, &SPerformanceOptimizerTab::GetResultsText)
				.Font(FCoreStyle::GetDefaultFontStyle("Bold", 11))
				.AutoWrapText(true)
			]
		]

		// Items
		+ SVerticalBox::Slot()
		.FillHeight(1.f)
		.Padding(12.f, 0.f, 12.f, 10.f)
		[
			SNew(SScrollBox)
			+ SScrollBox::Slot()
			[
				SAssignNew(ItemsBox, SVerticalBox)
			]
		]
	];

	// Scan as soon as the tab opens.
	RunPython(TEXT("ui_scan()"));
}

void SPerformanceOptimizerTab::RunPython(const FString& Call)
{
	IPythonScriptPlugin* Python = IPythonScriptPlugin::Get();
	if (!Python || !Python->IsPythonAvailable())
	{
		LastError = TEXT("Python is not available. Enable 'Python Editor Script Plugin' (Edit > Plugins) and restart the editor.");
		RequestRebuild();
		return;
	}

	const FString Command = FString::Printf(TEXT("import perf_optimizer as _perf_ui; _perf_ui.%s"), *Call);
	if (Python->ExecPythonCommand(*Command))
	{
		LastError.Reset();
	}
	else
	{
		LastError = TEXT("The Python call failed - see the Output Log. Is the Light Mobility Tool plugin enabled?");
	}

	LoadState();
	RequestRebuild();

	if (IsBusy() && !bPolling)
	{
		bPolling = true;
		RegisterActiveTimer(0.25f, FWidgetActiveTimerDelegate::CreateSP(this, &SPerformanceOptimizerTab::OnPollTimer));
	}
}

void SPerformanceOptimizerTab::LoadState()
{
	const FString Path = FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("PerformanceOptimizer"), TEXT("ui_state.json"));
	FString Text;
	if (!FFileHelper::LoadFileToString(Text, *Path))
	{
		return;
	}

	TSharedPtr<FJsonObject> Parsed;
	const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Text);
	if (FJsonSerializer::Deserialize(Reader, Parsed) && Parsed.IsValid())
	{
		State = Parsed;
	}
}

void SPerformanceOptimizerTab::RequestRebuild()
{
	// Rebuild on the next frame, never inside a child widget's own event handler.
	if (!bRebuildPending)
	{
		bRebuildPending = true;
		RegisterActiveTimer(0.f, FWidgetActiveTimerDelegate::CreateSP(this, &SPerformanceOptimizerTab::OnRebuildTimer));
	}
}

EActiveTimerReturnType SPerformanceOptimizerTab::OnRebuildTimer(double InCurrentTime, float InDeltaTime)
{
	bRebuildPending = false;
	RebuildItems();
	return EActiveTimerReturnType::Stop;
}

EActiveTimerReturnType SPerformanceOptimizerTab::OnPollTimer(double InCurrentTime, float InDeltaTime)
{
	LoadState();
	if (IsBusy())
	{
		return EActiveTimerReturnType::Continue;
	}
	bPolling = false;
	RequestRebuild();
	return EActiveTimerReturnType::Stop;
}

void SPerformanceOptimizerTab::RebuildItems()
{
	if (!ItemsBox.IsValid())
	{
		return;
	}
	ItemsBox->ClearChildren();

	const TArray<TSharedPtr<FJsonValue>>* Categories = PerfUI::Array(State, TEXT("categories"));
	if (!Categories)
	{
		return;
	}

	for (const TSharedPtr<FJsonValue>& CategoryValue : *Categories)
	{
		const TSharedPtr<FJsonObject> Category = CategoryValue.IsValid() ? CategoryValue->AsObject() : nullptr;
		if (!Category.IsValid())
		{
			continue;
		}

		ItemsBox->AddSlot()
		.AutoHeight()
		.Padding(0.f, 14.f, 0.f, 4.f)
		[
			SNew(STextBlock)
			.Text(FText::FromString(PerfUI::Str(Category, TEXT("name"))))
			.Font(FCoreStyle::GetDefaultFontStyle("Bold", 13))
		];

		if (const TArray<TSharedPtr<FJsonValue>>* Items = PerfUI::Array(Category, TEXT("items")))
		{
			for (const TSharedPtr<FJsonValue>& ItemValue : *Items)
			{
				const TSharedPtr<FJsonObject> Item = ItemValue.IsValid() ? ItemValue->AsObject() : nullptr;
				if (Item.IsValid())
				{
					ItemsBox->AddSlot()
					.AutoHeight()
					.Padding(0.f, 2.f)
					[
						MakeItemRow(Item)
					];
				}
			}
		}
	}
}

TSharedRef<SWidget> SPerformanceOptimizerTab::MakeItemRow(const TSharedPtr<FJsonObject>& Item)
{
	const FString Id = PerfUI::Str(Item, TEXT("id"));
	const bool bSafeId = PerfUI::IsSafeId(Id);
	const bool bToggle = PerfUI::Str(Item, TEXT("kind")) == TEXT("toggle");
	const bool bOn = PerfUI::Bool(Item, TEXT("enabled"));
	const bool bAvailable = PerfUI::Bool(Item, TEXT("available")) && bSafeId;
	const bool bCanSelect = PerfUI::Bool(Item, TEXT("can_select")) && bSafeId;
	const FString Risk = PerfUI::Str(Item, TEXT("visual_risk"));

	FString Info = FString::Printf(TEXT("Expected gain: %s   |   %s   |   Textures: %s"),
		*PerfUI::Str(Item, TEXT("gain")), *PerfUI::Str(Item, TEXT("scope")), *PerfUI::Str(Item, TEXT("textures")));
	if (PerfUI::Bool(Item, TEXT("auto")))
	{
		Info += TEXT("   |   Part of Auto Optimize");
	}
	if (PerfUI::Bool(Item, TEXT("unsaved")))
	{
		Info += TEXT("   |   NOT SAVED to project");
	}

	TSharedRef<SHorizontalBox> Controls = SNew(SHorizontalBox);
	if (bCanSelect)
	{
		Controls->AddSlot()
		.AutoWidth()
		.VAlign(VAlign_Center)
		.Padding(0.f, 0.f, 8.f, 0.f)
		[
			SNew(SButton)
			.Text(LOCTEXT("Select", "Select in level"))
			.ToolTipText(LOCTEXT("SelectTip", "Select the actors this refers to, to review them in the Details panel."))
			.IsEnabled(this, &SPerformanceOptimizerTab::IsIdle)
			.OnClicked_Lambda([this, Id]()
			{
				RunPython(FString::Printf(TEXT("ui_select('%s')"), *Id));
				return FReply::Handled();
			})
		];
	}
	if (bToggle)
	{
		Controls->AddSlot()
		.AutoWidth()
		.VAlign(VAlign_Center)
		[
			SNew(SCheckBox)
			.IsChecked(bOn ? ECheckBoxState::Checked : ECheckBoxState::Unchecked)
			.IsEnabled_Lambda([this, bAvailable]() { return bAvailable && IsIdle(); })
			.OnCheckStateChanged_Lambda([this, Id](ECheckBoxState NewState)
			{
				RunPython(FString::Printf(TEXT("ui_set('%s', %s)"), *Id,
					NewState == ECheckBoxState::Checked ? TEXT("True") : TEXT("False")));
			})
			[
				SNew(STextBlock).Text(bOn ? LOCTEXT("On", "On") : LOCTEXT("Off", "Off"))
			]
		];
	}
	else
	{
		Controls->AddSlot()
		.AutoWidth()
		.VAlign(VAlign_Center)
		[
			SNew(STextBlock)
			.Text(LOCTEXT("AdviceOnly", "Advice only"))
			.ToolTipText(LOCTEXT("AdviceTip", "Changing this automatically could alter the look of the production, so the tool only explains it."))
			.ColorAndOpacity(FSlateColor::UseSubduedForeground())
		];
	}

	return SNew(SBorder)
		.BorderImage(FAppStyle::GetBrush("ToolPanel.GroupBorder"))
		.Padding(FMargin(10.f, 8.f))
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot()
			.FillWidth(1.f)
			[
				SNew(SVerticalBox)
				+ SVerticalBox::Slot()
				.AutoHeight()
				[
					SNew(SHorizontalBox)
					+ SHorizontalBox::Slot()
					.AutoWidth()
					[
						SNew(STextBlock)
						.Text(FText::FromString(PerfUI::Str(Item, TEXT("name"))))
						.Font(FCoreStyle::GetDefaultFontStyle("Bold", 11))
					]
					+ SHorizontalBox::Slot()
					.AutoWidth()
					.Padding(10.f, 0.f, 0.f, 0.f)
					.VAlign(VAlign_Center)
					[
						SNew(STextBlock)
						.Text(FText::FromString(FString::Printf(TEXT("Visual change: %s"), *Risk)))
						.Font(FCoreStyle::GetDefaultFontStyle("Bold", 9))
						.ColorAndOpacity(FSlateColor(PerfUI::RiskColor(Risk)))
					]
				]
				+ SVerticalBox::Slot()
				.AutoHeight()
				.Padding(0.f, 2.f, 0.f, 0.f)
				[
					SNew(STextBlock)
					.Text(FText::FromString(Info))
					.Font(FCoreStyle::GetDefaultFontStyle("Regular", 8))
					.ColorAndOpacity(FSlateColor::UseSubduedForeground())
					.AutoWrapText(true)
				]
				+ SVerticalBox::Slot()
				.AutoHeight()
				.Padding(0.f, 4.f, 0.f, 0.f)
				[
					SNew(STextBlock)
					.Text(FText::FromString(PerfUI::Str(Item, TEXT("detail"))))
					.AutoWrapText(true)
				]
				+ SVerticalBox::Slot()
				.AutoHeight()
				.Padding(0.f, 4.f, 0.f, 0.f)
				[
					SNew(STextBlock)
					.Text(FText::FromString(PerfUI::Str(Item, TEXT("suggestion"))))
					.ColorAndOpacity(FSlateColor(PerfUI::StatusColor(PerfUI::Str(Item, TEXT("status")))))
					.AutoWrapText(true)
				]
			]
			+ SHorizontalBox::Slot()
			.AutoWidth()
			.VAlign(VAlign_Center)
			.Padding(12.f, 0.f, 0.f, 0.f)
			[
				Controls
			]
		];
}

bool SPerformanceOptimizerTab::IsBusy() const
{
	return PerfUI::Bool(State, TEXT("busy"));
}

bool SPerformanceOptimizerTab::IsViewportRealtime() const
{
	return GCurrentLevelEditingViewportClient != nullptr && GCurrentLevelEditingViewportClient->IsRealtime();
}

FText SPerformanceOptimizerTab::GetHeaderText() const
{
	return FText::FromString(PerfUI::Str(State, TEXT("header_text")));
}

FText SPerformanceOptimizerTab::GetStatusText() const
{
	if (!LastError.IsEmpty())
	{
		return FText::FromString(LastError);
	}
	return FText::FromString(PerfUI::Str(State, TEXT("status_text")));
}

FText SPerformanceOptimizerTab::GetResultsText() const
{
	return FText::FromString(PerfUI::Str(State, TEXT("results_text")));
}

EVisibility SPerformanceOptimizerTab::GetResultsVisibility() const
{
	return PerfUI::Str(State, TEXT("results_text")).IsEmpty() ? EVisibility::Collapsed : EVisibility::Visible;
}

FReply SPerformanceOptimizerTab::OnScanClicked()
{
	RunPython(TEXT("ui_scan()"));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnAutoClicked()
{
	RunPython(FString::Printf(TEXT("ui_auto_start(viewport_realtime=%s, include_low=%s)"),
		IsViewportRealtime() ? TEXT("True") : TEXT("False"),
		bIncludeLowImpact ? TEXT("True") : TEXT("False")));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnMeasureClicked()
{
	RunPython(FString::Printf(TEXT("ui_measure(viewport_realtime=%s)"),
		IsViewportRealtime() ? TEXT("True") : TEXT("False")));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnCancelClicked()
{
	RunPython(TEXT("ui_cancel()"));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnSaveClicked()
{
	RunPython(TEXT("ui_save_project()"));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnRevertClicked()
{
	RunPython(TEXT("ui_revert_all()"));
	return FReply::Handled();
}

FReply SPerformanceOptimizerTab::OnReportClicked()
{
	RunPython(TEXT("ui_open_report()"));
	return FReply::Handled();
}

#undef LOCTEXT_NAMESPACE
